spring:
    # h2:
    #     console:
    #         enabled: false
    #         path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        # show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/balance
        # url: jdbc:h2:mem:testdb
        username: postgres
        password: balance